# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{railsbike_ext}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Alexander Kirillov}]
  s.date = %q{2011-08-20}
  s.description = %q{Extension for railsbike}
  s.email = %q{saratovsource@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/railsbike_ext.rb",
    "test/helper.rb",
    "test/test_railsbike_ext.rb"
  ]
  s.homepage = %q{http://github.com/saratovsource/railsbike_ext}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{Extension for railsbike}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.9"])
      s.add_runtime_dependency(%q<mongoid>, ["~> 2.0.2"])
      s.add_runtime_dependency(%q<bson_ext>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<haml>, ["= 3.1.2"])
      s.add_runtime_dependency(%q<sass>, ["= 3.1.2"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<linecache>, ["= 0.43"])
      s.add_development_dependency(%q<cucumber-rails>, ["= 1.0.2"])
      s.add_development_dependency(%q<pickler>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.9"])
      s.add_dependency(%q<mongoid>, ["~> 2.0.2"])
      s.add_dependency(%q<bson_ext>, ["~> 1.3.0"])
      s.add_dependency(%q<haml>, ["= 3.1.2"])
      s.add_dependency(%q<sass>, ["= 3.1.2"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<linecache>, ["= 0.43"])
      s.add_dependency(%q<cucumber-rails>, ["= 1.0.2"])
      s.add_dependency(%q<pickler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.9"])
    s.add_dependency(%q<mongoid>, ["~> 2.0.2"])
    s.add_dependency(%q<bson_ext>, ["~> 1.3.0"])
    s.add_dependency(%q<haml>, ["= 3.1.2"])
    s.add_dependency(%q<sass>, ["= 3.1.2"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<linecache>, ["= 0.43"])
    s.add_dependency(%q<cucumber-rails>, ["= 1.0.2"])
    s.add_dependency(%q<pickler>, [">= 0"])
  end
end

